# this sets up "context variables" (in this case name and version) that
# can later be used in Jinja expressions
context:
  version: 0.1.0
  name: faim-fiji

# top level package information (name and version)
package:
  name: ${{ name }}
  version: ${{ version }}

# location to get the source from
source:
  - url: https://downloads.imagej.net/fiji/archive/20240318-1717/fiji-nojre.zip
    sha256: 3a8641d861785890db7a5bcd88b29c32c4f5a316ac6c05a8acbf706b6cad1a28
    target_directory: fiji


# build number (should be incremented if a new build is made, but version is not incrementing)
build:
  number: 1
  script:
  - if: linux
    then: build.sh
  - if: osx
    then: build-osx.sh
  - if: win
    then: build.bat


# the requirements at build and runtime
requirements:
  host:
    - openjdk<=9
  run:
    - openjdk<=9

# tests to validate that the package works as expected
tests:
  - package_contents:
      files:
        - if: win
          then: ImageJ-win64.exe
        - if: linux
          then: ImageJ-linux64
        - if: osx
          then: Contents/MacOS/ImageJ-macosx
        - jars/mobie-viewer-fiji-4.4.2.jar


# information about the package
about:
  homepage: https://github.com/fmi-faim/faim-fiji
  license: GPL-3.0
  summary: 'Custom Fiji bundle for distribution via conda'
  description: |
    Fiji (Is Just ImageJ) deployed as a conda package,
    with some update sites activated that are commonly used
    at the Friedrich Miescher Institute for Biomedical Research (FMI)
  repository: https://github.com/fmi-faim/faim-fiji
  documentation: https://github.com/fmi-faim/faim-fiji

# the below is conda-forge specific!
extra:
  recipe-maintainers:
    - imagejan
